package com.es.marocapp.model.responses

data class GetPreLoginDataResponse(
    val amountConversionValue: String,
    val androidOtpExpiryTime: String,
    val androidOtpLength: Int,
    val bankDomainForRegistration: String,
    val cilLength: String,
    val cilRegex: String,
    val cnLength: String,
    val cnRegex: String,
    val consumerRegistrationProfile: String,
    val currencyOnEwp: String,
    val currencyToShow: String,
    val dateFormat: String,
    val description: String,
    val faqs: String,
    val genderList: List<String>,
    val helpLineNumber: String,
    val iosOtpExpiryTime: String,
    val iosOtpLength: Int,
    val msisdnLength: String,
    val msisdnMaxLength: String,
    val msisdnPrefix: String,
    val msisdnRegex: String,
    val numberOfTransactions: String,
    val publicKey: Any,
    val quickAmounts: List<String>,
    val quickRechargeAmounts: List<String>,
    val responseCode: String,
    val termsAndConditions: String,
    val url: String,
    val version: String,
    val postpaidBillFixedRegex:String,
    val postpaidBillInternetRegex:String,
    val postpaidBillMobileRegex:String
)